### ISSUE TITLE
Make data::data_channel::DataChannel implement tokio::io AsyncRead and AsyncWrite traits

### ISSUE THREAD

**Issue by tedsteen** [webrtc-rs/webrtc#110]
For better interoperability with tokio

**Comment by melekes** [comment]
@tedsteen did you end up implementing it yourself?

**Comment by tedsteen** [comment]
> @tedsteen did you end up implementing it yourself? if so, can you share the code? I'm currently doing the same thing.

No I didn't, would still be a nice addition imo

**Comment by melekes** [comment]
I will work on that then

**Comment by melekes** [comment]
Opened https://github.com/webrtc-rs/sctp/pull/9

**Comment by melekes** [comment]
Sorry, one more thing needs to be done - https://github.com/webrtc-rs/data/pull/4. Once it's merged, this issue can be closed.
