### ISSUE TITLE
[examples] Reading stdin: stuck with line longer than 1024 characters in MacOS

### ISSUE THREAD

**Issue by rainliu** [webrtc-rs/webrtc#134]
due to this limits in Mac OS, many examples, i.e., ortc, data-channels-create, will be stuck when paste answer to stdin.

Linux works fine.

**Comment by qbx2** [comment]
I use `pbpaste | cargo run ...`

**Comment by rainliu** [comment]
thanks for the suggestion. Just searched the following blog to show how to use it:

How to use pbcopy and pbpaste:
https://medium.com/@codenameyau/how-to-copy-and-paste-in-terminal-c88098b5840d

**Comment by capital-G** [comment]
The problem persists on e.g. https://github.com/webrtc-rs/webrtc/tree/master/examples/examples/data-channels-create which relies on a runtime-dependent input from a response.

I was not aware of this issue and it took me around 1 hour to figure out that [macOS has such a limit](https://superuser.com/questions/264407/macosx-10-6-7-cuts-off-stdin-at-1024-chars) - maybe it would be good to add a disclaimer to the examples?
I would be interested in other ways to inject the response code in runtime in an easy manner - maybe watch for a file which holds the payload?
