### ISSUE TITLE
UDPMux not controllable through SettingsEngine 

### ISSUE THREAD

**Issue by rmst** [webrtc-rs/webrtc#135]
I saw that UDPMux support was added in v0.3.0. However, in the SettingsEngine it's still commented out (https://github.com/webrtc-rs/webrtc/blob/494b052be4ff9d9ec3b1fd43a2ddd8e0c1b0c56e/src/api/setting_engine/mod.rs#L72). What's the correct way to enable UDPMux currently?

**Comment by rainliu** [comment]
use pub(crate) udp_network: UDPNetwork,

https://github.com/webrtc-rs/webrtc/blob/494b052be4ff9d9ec3b1fd43a2ddd8e0c1b0c56e/src/api/setting_engine/mod.rs#L74

**Comment by k0nserv** [comment]
Hey 👋🏼,

So we should probably remove that line. When I implemented UDP mux I didn't port the logic directly from Go. Instead I modeled the UDP networking in a way that reflects the mutually exclusive nature of using either many ephemeral UDP sockets bound to random ports or using a single UDP socket.

This is described in the documentation for [`UDPNetwork`](https://github.com/webrtc-rs/ice/blob/main/src/udp_network.rs#L40-L52).

The ping_pong example in the ICE crate shows how to use [muxxing](https://github.com/webrtc-rs/ice/blob/main/examples/ping_pong.rs#L180-L186) vs [ephemeral ports](https://github.com/webrtc-rs/ice/blob/main/examples/ping_pong.rs#L188)

**Comment by rmst** [comment]
Ah perfect! Thank you both for that super quick response!

**Comment by rainliu** [comment]
just updated doc too: https://github.com/webrtc-rs/webrtc/commit/f45bb4a35ffd13216cf182c1d699784a10764426
