### ISSUE TITLE
Miss of built-in packet loss handling solutions

### ISSUE THREAD

**Issue by aegroto** [webrtc-rs/webrtc#138]
Hello,

I'm trying to use this library to make some trials about real-time desktop streaming, but the video stream is nearly immediately corrupted because of packet loss/reordering. What's the suggested approach to handle this kind of issues? I've explored the examples but I can't see anything related to handling network errors, maybe I've missed it.

For anyone interested on exploring the project, this is the repo and the source code (right now mostly undocumented): https://github.com/aegroto/remotia/tree/webrtc-nohardrework

**Comment by rainliu** [comment]
Does configure_nack help your case? https://github.com/webrtc-rs/webrtc/blob/master/src/api/interceptor_registry/mod.rs#L40

**Comment by aegroto** [comment]
I will give it a try once I can and let you know, thanks!

**Comment by giangndm** [comment]
I also have the same issues with NACK.
When checking the interceptor module, maybe have an issue on rtcp reader flow when we have more than a stream.

**Comment by rainliu** [comment]
@aegroto, have you tried configure_nack? Does this help for your packet loss case?

**Comment by aegroto** [comment]
Hello, I'm sorry but I had no chance yet as I've been busy with other experiments.

@giangndm I'm not sure we've got the same issues, my code doesn't make advantage of NACKs at all.
