### ISSUE TITLE
Capture just one frame as an image?

### ISSUE THREAD

**Issue by D1plo1d** [webrtc-rs/webrtc#147]
I'm looking to create a time-lapse from a WebRTC that needs to be externally triggered to capture frames at non-regular intervals (resulting in an mjpeg or similar). Is it possible to get a single frame from a WebRTC video stream with webrtc-rs?

**Comment by k0nserv** [comment]
You'll need to keep a buffer with the latest keyframe + all subsequent delta packets around, then when you want to capture you should be able to feed all of this data to a decoder and get a single decoded frame.
