### ISSUE TITLE
Failure to reuse mid

### ISSUE THREAD

**Issue by algesten** [webrtc-rs/webrtc#162]
The test case is using Chrome to webrtc-rs.

1. Add mic track in Chrome.
2. Remove mic track.
3. Re-add mic track.

The resulting SDP dance is here:

```
Chrome OFFER (add mic)
  m=audio 9 UDP/TLS/RTP/SAVPF 111 63 103 104 9 0 8 106 105 13 110 112 113 126
  a=mid:1
  a=sendonly

webrtc-rs ANSWER
  m=audio 9 UDP/TLS/RTP/SAVPF 111
  a=mid:1
  a=recvonly

Chrome OFFER (remove mic)
  m=audio 9 UDP/TLS/RTP/SAVPF 111 63 103 104 9 0 8 106 105 13 110 112 113 126
  a=mid:1
  a=inactive

webrtc-rs ANSWER
  m=audio 9 UDP/TLS/RTP/SAVPF 111
  a=mid:1
  a=inactive

Chrome OFFER (add mic)
  m=audio 9 UDP/TLS/RTP/SAVPF 111 63 103 104 9 0 8 106 105 13 110 112 113 126
  a=mid:1
  a=sendonly

webrtc-rs ANSWER
  m=audio 9 UDP/TLS/RTP/SAVPF 111
  a=mid:1
  a=inactive  <---------- WRONG!
```

In this scenario Chrome tries to re-use `mid=1` going from `a=inactive` to `a=sendonly`. However webrtc-rs seems to not keep the `a=inactive`.

I'm trying to figure out where in the code this happens.

**Comment by algesten** [comment]
`replaceTrack(null)` should not make transceiver `inactive`, but we can set direction to `inactive` manually in this case.

Either way, `inactive` is not the same as `stopped`.

**Comment by k0nserv** [comment]
PR to implement a paused state for `RTPReceiver` here https://github.com/webrtc-rs/webrtc/pull/201

**Comment by k0nserv** [comment]
This is fixed
