### ISSUE TITLE
How to using MediaCodec(h264,Android)'s OutputBufferr

### ISSUE THREAD

**Issue by cd711** [webrtc-rs/webrtc#190]
Specific:
I recv h264 frame data from scrcpy(https://github.com/Genymobile/scrcpy/blob/master/server/src/main/java/com/genymobile/scrcpy/ScreenEncoder.java)

and write with track,
I tried TrackLocalStaticSample::writeSample and TrackLocalStaticRTP::write to writing raw data
but it's not work

I hope to get your help

Thank you very match

**Comment by k0nserv** [comment]
You want `TrackLocalStaticSample` I suspect. It expects H264 NALUs in the Annex B bitstream format. The format is described towards the end of the [h.264 specification](https://www.itu.int/rec/dologin_pub.asp?lang=e&id=T-REC-H.264-202108-I!!PDF-E&type=items) and involves adding sequences of `0x000001` or `0x00000001` between each h.264 NALU. This might already be the format that scrcpy produces or you might have to parse their format and convert it to the annex bitstream.

`TrackLocalStaticRTP` is not suitable since it expects data in the h.264 RTP payload format

**Comment by cd711** [comment]
thanks
I saved the configuration frame (the first buffer) and splice it to the front of each keyFrame. **It works!**

`
// scrcpy parse process
let mut stream = TcpStream::connect("localhost:3111").await.unwrap();
{
    // skip 1 byte
    use tokio::io::AsyncReadExt;
    let ref mut tmp = [0u8; 1];
    stream.read(tmp).await.unwrap();
}
// device info
let mut tmp = [0u8; 69];
let mut r_size = 0usize;
while r_size < 68 {
    use tokio::io::AsyncReadExt;
    r_size += stream.read(&mut tmp[r_size..]).await?;
}
let cstr = unsafe { CString::from_raw(tmp[0..64].as_ptr() as *mut i8) };
let name = cstr.to_str().unwrap();
// let name = cstr
let mut c = Cursor::new(&mut tmp[64..]);
let w = c.read_u16::<BigEndian>().unwrap();
let h = c.read_u16::<BigEndian>().unwrap();
println!("device:{} screen:{}x{}", name, w, h);

let mut sps_pps = vec![];
let ones = Duration::from_millis(1); // every frame's duration. but ....
log::info!("rtp start");
loop {
   // frame meta
    let mut head = [0u8; 12];
    let mut r_size = 0usize;
    while r_size < 12 {
        use tokio::io::AsyncReadExt;
        r_size += stream.read(&mut head[r_size..]).await?;
    }
    let mut c = Cursor::new(&head);

    let pts = c.read_u64::<BigEndian>().unwrap();
    let p_size = c.read_u32::<BigEndian>().unwrap() as usize;

    let mut buff = vec![];
    if p_size > 0 {
        buff.resize(p_size, 0);
        let mut r_size = 0usize;
        while r_size < p_size {
            use tokio::io::AsyncReadExt;
            r_size += stream.read(&mut buff[r_size..]).await?;
        }
    }

    if (pts & PACKET_FLAG_CONFIG) != 0 { // config frame
        sps_pps = buff;
        log::debug!("video info change");
        continue;
    }

    if buff.len() > 4 && buff[4] == 0x65 {  // key frame
        // let pts = PACKET_FLAG_KEY_FRAME & pts;
        // println!("pts:{}", pts);
        let mut buff_1 = Vec::from(sps_pps.as_slice());
        buff_1.append(&mut Vec::from(buff));
        if let Err(e) = track
            .write_sample(&Sample {
                data: Bytes::from(buff_1),
                duration: ones,
                // timestamp: SystemTime::now(),
                // packet_timestamp: (ppp / 1000u64) as u32,
                ..Default::default()
            })
            .await
        {
            log::error!("send key frame error:{:?}", e);
        }
    } else {
        if let Err(e) = track
            .write_sample(&Sample {
                data: Bytes::from(buff),
                duration: ones,
                // timestamp: SystemTime::now(),
                // packet_timestamp: (pts / 1000u64) as u32,
                ..Default::default()
            })
            .await
        {
            log::error!("send frame error:{:?}", e);
        }
    }
`
??? same question
I don't quite understand some members of sample
"timestamp","packet_timestamp" doesn't seem to be used (check the source code).

What is the real meaning of duration? (appears to be the maximum delay?)

**Comment by k0nserv** [comment]
Yes you are correct about a bunch of the fields aren't used. I'm not sure why that is unfortunately, but the duration field is important.

Duration should be the duration of the sample in question and it's used for the RTP timestamps. If you have fixed FPS you can probably hardcode this value to 1000/{fps}ms. I believe h.264 also carries its own timing information inside the NALUs which is probably why it still works anyway.

**Comment by cd711** [comment]
I'm thinking
If there is an audio track. How can the audio and video be synchronized(without pts)

**Comment by zhenguang** [comment]
@cd711 你有成功把scrcpy做上Webrtc吗？
