### ISSUE TITLE
Current status of data channel functionality?

### ISSUE THREAD

**Issue by ranaya-formant** [webrtc-rs/webrtc#196]
I'm trying to figure out how stable data channel is right now in this project, would you consider it alpha? beta? production? I think there's a strong interest in webrtc-rs only for data channel.  Perhaps you can reflect the current maturity levels of data channels separate from media?

**Comment by ValorZard** [comment]
I'd second on this. A lot of people are only interested in this crate for the data channel aspect, since webrtc is very useful for game developement, and as a sort of "web-udp".

**Comment by k0nserv** [comment]
Definitely at least beta. We are using this project in production and while we have encountered bugs and issues none of them have been in data channels. Our use case is fairly limited, only using them for moderately sized JSON serialized messages. @melekes has been working a lot on improving them.

There is a known throughput problem that need to be investigated: https://github.com/webrtc-rs/webrtc/issues/101
