### ISSUE TITLE
Buffer too small (16 bytes) to fit a FeedbackPacket. Minimum size = 18

### ISSUE THREAD

**Issue by kraigher** [webrtc-rs/webrtc#215]
When running against chromium the following message appears:
```
Buffer too small (16 bytes) to fit a FeedbackPacket. Minimum size = 18
```

It is caused by the chromium code expecting a FeedbackPacket with at least one chunk but webrtc-rs sends an empty feedback packet.
https://chromium.googlesource.com/external/webrtc/+/HEAD/modules/rtp_rtcp/source/rtcp_packet/transport_feedback.cc#38

```cpp
// Payload size:
// * 8 bytes Common Packet Format for RTCP Feedback Messages
// * 8 bytes FeedbackPacket header.
// * 2 bytes for one chunk.
constexpr size_t kMinPayloadSizeBytes = 8 + 8 + 2;
````

This happens when using the default `register_default_interceptors` which does `configure_twcc_receiver_only` that adds only a receiver. What happens is there is no sender which can call `recorder.record` and thus the twcc receiver will build empty feedback packets.

I noticed that Pion adds a TWCC sender by default instead of a receiver:
https://github.com/pion/webrtc/blob/master/interceptor.go#L29

**Comment by k0nserv** [comment]
It was 🎉
