### ISSUE TITLE
Interface list is broken on Android 11+

### ISSUE THREAD

**Issue by chayleaf** [webrtc-rs/webrtc#272]
See https://github.com/messense/if-addrs/issues/14

TLDR: on Android 11, `getifaddrs` is working, but the method used in `webrtc-util` doesn't. Since `getifaddrs` doesn't work on old Android versions (seemingly 6 and below?), perhaps both methods should be tried?

Weirdly, the current method works just fine for me on an emulator, but not on a physical device

**Comment by jamilbk** [comment]
See https://github.com/webrtc-rs/webrtc/pull/484 -- closed it because we haven't done much testing with it yet, but seems to resolve the issue you note.
