### ISSUE TITLE
The track id received by the browser is not the track id of webrtc-rs

### ISSUE THREAD

**Issue by mantou132** [webrtc-rs/webrtc#274]
Steps to reproduce:
1. run broadcast example
2. publish stream
3. open other browser, join the broadcast
4. check video1 `srcObject` stream and track id

```rust
let local_track = Arc::new(TrackLocalStaticRTP::new(
    track.codec().await.capability,
    "video".to_owned(),
    "webrtc-rs".to_owned(),
));
let _ = local_track_chan_tx2.send(Arc::clone(&local_track)).await;
```

<img width="769" alt="Screen Shot 2022-08-30 at 16 27 07" src="https://user-images.githubusercontent.com/3841872/187388661-b230a9ae-71ed-4cf7-9085-27df94480a93.png">

**Comment by k0nserv** [comment]
This is according to the specification, it used to be the case that the track IDs matched on the receiving end but this is no longer mandated by the specification.

See step 2 of ["Create an RTCRtpReceiver"](https://www.w3.org/TR/webrtc/#dfn-create-an-rtcrtpreceiver)

> Let track be a new [MediaStreamTrack](https://www.w3.org/TR/mediacapture-streams/#dom-mediastreamtrack) object [[GETUSERMEDIA](https://www.w3.org/TR/webrtc/#bib-getusermedia)]. The source of track is a remote source provided by receiver. Note that the track.id is generated by the [user agent](https://www.w3.org/TR/webrtc/#dfn-user-agent) and does not map to any track IDs on the remote side.

**Comment by mantou132** [comment]
thanks. I need to match local track and remote track, I found a way to do it.

https://stackoverflow.com/questions/65408744/in-webrtc-how-do-i-label-a-local-mediastream-so-that-a-remote-peer-can-identify

**Comment by k0nserv** [comment]
Sounds good, using streams(which are reflected on the remote side) is a good way to do this.
