### ISSUE TITLE
Examples broken

### ISSUE THREAD

**Issue by stellanhaglund** [webrtc-rs/webrtc#280]
Hi, when I try to run the `play-from-disk-*` i get 
`Error: EOF while parsing a value at line 1 column 0`
I tried with different ivf files and h264 files but there's no difference.

**Comment by stellanhaglund** [comment]
I'm on an intel mac btw.

**Comment by stellanhaglund** [comment]
Same thing with `save-to-disk-*`

**Comment by k0nserv** [comment]
Can you provide a stacktrace using `RUST_BACKTRACE=1` and the full command you are running?

**Comment by stellanhaglund** [comment]
This was completely my mistake, I was setting the `BROWSER_SDP` wrong so it weren't able to find the SDP.
Sorry!

**Comment by k0nserv** [comment]
Np, thanks for being a good open source citizen and raising an issue when you thought you'd found something wrong.

Feel free to join the [discord](https://discord.gg/4Ju8UHdXMs) if you wanna ask more questions
