### ISSUE TITLE
Error on depacketize an audio/opus rtp

### ISSUE THREAD

**Issue by Mnwa** [webrtc-rs/webrtc#305]
Hey! I'm using your example save-to-disk-h264 and audio stream fails after a few seconds.
It's happens because I got packet with empty payload:
`Packet { header: Header { version: 2, padding: true, extension: true, marker: false, payload_type: 111, sequence_number: 3069, timestamp: 2534425974, ssrc: 3109151906, csrc: [], extension_profile: 48862, extensions: [Extension { id: 3, payload: b"\0\x03" }] }, payload: b"" }`

Is it ok to ignore these error?

**Comment by k0nserv** [comment]
Hey, good timing. I've just been exploring this last week. These are padding packets that libWebRTC sends periodically to ensure send rate is stable, so they're fine to ignore. It's also worth noting that the save to disk example is a bit naive since it doesn't reorder incoming packets.
