### ISSUE TITLE
[Interceptor] panic in calculate_rtt_ms

### ISSUE THREAD

**Issue by muenchow** [webrtc-rs/webrtc#347]
When leaving a webrtc connection running for a longer time, a panic was emitted see log below.
```panicked at 'attempt to subtract with overflow', /home/maxmuen/.cargo/registry/src/github.com-1ecc6299db9ec823/interceptor-0.8.0/src/stats/interceptor.rs:737:15```

**Comment by k0nserv** [comment]
Hey @muenchow, 

Thanks for reporting this. I guess it can happen. We already handle rtt as an optional so it should be easy enough to change the signature of `calculate_rtt_ms` to `fn calculate_rtt_ms(now: u32, delay: u32, last_report: u32) -> Option<f64>` and use `checked_sub` instead as a fix.

Would you be open to contributing?

**Comment by chuigda** [comment]
Let me help.

**Comment by k0nserv** [comment]
Fixed in #350. Thanks @muenchow for reporting and @chuigda for fixing
