### ISSUE TITLE
Force high bitrate for incoming video

### ISSUE THREAD

**Issue by Wicpar** [webrtc-rs/webrtc#353]
Hi, 
I'm using a modified version of the broadcast example to achieve just that in an production environment, is there a way to force a high bitrate for incoming video ?

**Comment by k0nserv** [comment]
`RTCRtpSender.sendEncodings` with `maxBitrate` can be used to control it somewhat. However, browsers will typically use available bandwidth estimates and other network signals to adjust the bitrate on the fly.


In my experience browsers will default to about 2.5Mbps for video streams but then adjust downwards if the network conditions aren't sufficiently good

**Comment by Wicpar** [comment]
i see, i'm already doing that, at 10Mbits, depending on the device the video and audio is still very compressed, i was wondering if there is a way in sdp or something else withg server side hackery

**Comment by k0nserv** [comment]
I'm not sure. I think there's some SDP attribute that might help. Also worth checking `chrome://webrtc-internals` which will contain information about target bitrate and constraints that are causing the bitrate to not be as high as you want(assuming you are using a browser to send)

**Comment by Wicpar** [comment]
So with further usage it looks like the bitrate is high enough with the setEncoding max bitrate, the rest is generally bound to the available bandwidth or encoding performance. Closing for now.
