### ISSUE TITLE
Bad semver bump in latest release

### ISSUE THREAD

**Issue by thomaseizinger** [webrtc-rs/webrtc#412]
I haven't found the exact problem yet but one of your users posted that they have started hitting compilation errors originating in webrtc: https://github.com/libp2p/rust-libp2p/discussions/3526

I think what might have happened is that in the recent release, the version of one of the crates did not receive a correct semver bump. `rust-libp2p` is - similar to `webrtc` - a workspace with many crates. What happened to us previously is that we accidentally released something as a patch version despite one of the workspace dependencies having received a minor bump AND that dependency was part of the public API. I don't know how many crates participated in the last release but that might be a good starting point to look for the issue :)

**Comment by thomaseizinger** [comment]
The issue is reproducible if you create a new crate, depend on `webrtc 0.6` and try to compile. The culprit seems to be the release of `webrtc-data 0.6.1`. That one pulls in `webrtc-sctp 0.8` which is incompatible with `webrtc-sctp 0.7`.

Running `cargo update -p webrtc-data --precise 0.6.0` temporarily fixes the issue.

**Comment by yngrtc** [comment]
fixed as suggested. Thanks for identifying this issue.

**Comment by nemosupremo** [comment]
I also seem to be hitting this issue with `webrtc 0.5.1`.

**Comment by melekes** [comment]
@yngrtc could we similarly yank interceptor 0.8.1 & 0.8.2 and rtcp 0.7.1 & 0.7.2 versions and release interceptor 0.9.0 and rtcp 0.8.0?

**Comment by yngrtc** [comment]
> @yngrtc could we similarly yank interceptor 0.8.1 & 0.8.2 and rtcp 0.7.1 & 0.7.2 versions and release interceptor 0.9.0 and rtcp 0.8.0?

done.
