### ISSUE TITLE
`RTCPeerConnection::close` no longer returns a `Send` future

### ISSUE THREAD

**Issue by thomaseizinger** [webrtc-rs/webrtc#413]
I am not sure if this change was on purpose, but in the latest release, the `RTCPeerConnection::close` function returns a future that is no longer `Send` which effectively makes this unusable with most executors that send tasks between worker threads.

See https://github.com/libp2p/rust-libp2p/actions/runs/4280630599/jobs/7453106193 for an example compile output.

The underlying issue seems to be that `RTCRtpTransceiver::stop` holds a mutex lock across an await point. Is that Mutex even necessary? None of the functions within `RTCRtpTransceiver` take `&mut self` so you should be fine without the Mutex?

**Comment by kolserdav** [comment]
Maybe this is related to this issue https://github.com/webrtc-rs/webrtc/issues/422

**Comment by thomaseizinger** [comment]
> Maybe this is related to this issue #422

It seems related yes. #422 was closed though. Did a fix land in `master` for this?

**Comment by kolserdav** [comment]
> > Maybe this is related to this issue #422
> 
> It seems related yes. #422 was closed though. Did a fix land in `master` for this?

No, it's still in progress, now I've reopened it.

**Comment by thomaseizinger** [comment]
To avoid this in the future, it might be worth looking at activating the following clippy lint: https://rust-lang.github.io/rust-clippy/master/#future_not_send

**Comment by thomaseizinger** [comment]
Fixed by https://github.com/webrtc-rs/webrtc/pull/429.
