### ISSUE TITLE
Example of working with AV1

### ISSUE THREAD

**Issue by stephenbaldwin** [webrtc-rs/webrtc#441]
I've attempted to adjust the example using VP8 to using AV1 Mime type and am getting an unsupported codec error. Do you have an example that uses AV1?

**Comment by kenaniah** [comment]
@stephenbaldwin when you create a video track, you can specify the codec to use like so:

```rust
// Create a video track
let video_track = Arc::new(TrackLocalStaticSample::new(
    RTCRtpCodecCapability {
        mime_type: "video/AV1".to_owned(),
        ..Default::default()
    },
    "video".to_owned(),
    "webrtc-rs".to_owned(),
));
```

If your other client is a web browser, you can see what codecs are supported by running the following Javascript code in that browser's console:

```javascript
RTCRtpReceiver.getCapabilities("video").codecs // (reference the mimeType field)
```

**Comment by stephenbaldwin** [comment]
Thank you!
