### ISSUE TITLE
fix Github Actions's fmt --all -- --check

### ISSUE THREAD

**Issue by rainliu** [webrtc-rs/webrtc#5]
cargo fmt --all -- --check

/usr/share/rust/.cargo/bin/cargo fmt --all -- --check
thread 'main' panicked at 'bad span: `.`: ``', src/tools/rustfmt/src/source_map.rs:52:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'bad span: `.`: ``', src/tools/rustfmt/src/source_map.rs:52:13

**Comment by rainliu** [comment]
@TaKO8Ki, 

Could you take a look?

**Comment by TaKO8Ki** [comment]
@rainliu 
Ok. I'm going to tackle this issue!
