### ISSUE TITLE
Has anyone written a sampler?

### ISSUE THREAD

**Issue by falconmick** [webrtc-rs/webrtc#50]
Hi all!

Probably not the best place to ask but I also don’t know where else. I am in the process of writing a video muxer which reads RTP streams and outputs them via OpenGL. Given I am using pion as the WebRTC side of things (for now, but given my OpenGL app is rust based I am able to use the RTP package from this org) I am basing my approach on the. ion-avp builder https://github.com/pion/ion-avp/blob/master/pkg/builder.go

So my question really is, has anyone else done this? I’m currently up to the part where I’m implementing the build loop and I’m discovering how much work there will be to port everything (namely the Sampler) so I was curious maybe sombody else has also tried this? Just hate doubling up the effort if someone smarter than me has already done the work :))

cheers
Michael.

**Comment by falconmick** [comment]
I feel like this would be better suited for a discord or slack. Would you be open to using one of the two?

**Comment by rainliu** [comment]
We have already setup discord: https://discord.gg/4Ju8UHdXMs.

**Comment by falconmick** [comment]
Thanks will move this
