### ISSUE TITLE
GStreamer based webkit2gtk fails with `Incoming unhandled RTCP ssrc(...), on_track will not be fired`

### ISSUE THREAD

**Issue by paultag** [webrtc-rs/webrtc#533]
Thank you for maintaining `webrtc-rs`! We really appreciate your work over at [Zoo/@KittyCAD](https://github.com/KittyCAD).

I've hit an issue that's a bit outside my ability to instrument at the moment, I couldn't find a related issue on this repo, and have only found one [related isue on pion/webrtc](https://github.com/pion/webrtc/issues/1021) that was [fixed in Feb 2020](https://github.com/pion/webrtc/commit/8c7bd6670689d07a11a9893ce3cfc39f11aa8a77) that I don't fully understand the mechanics of yet.

I've been trying out `webkit2gtk` (both through tauri and directly) to see if I can get a good negotiation with a `webrtc-rs` backend.

I'm going to do some investigation to try and narrow this down a bit more, but in case anyone else has hit this same issue, or someone otherwise recognizes whats going on, we'd be very interested in contributing back a fix.

```
  2024-02-14T18:28:51.053423Z  WARN webrtc::peer_connection::peer_connection_internal: Incoming unhandled RTCP ssrc(3057885015), on_track will not be fired
    at /home/paultag/.cargo/registry/src/index.crates.io-6f17d22bba15001f/webrtc-0.9.0/src/peer_connection/peer_connection_internal.rs:322


  2024-02-14T18:28:55.081505Z  WARN webrtc::peer_connection::peer_connection_internal: Failed to accept RTCP SessionSRTP has been closed
    at /home/paultag/.cargo/registry/src/index.crates.io-6f17d22bba15001f/webrtc-0.9.0/src/peer_connection/peer_connection_internal.rs:318
```

Thanks again for all you do! This library is great!

**Comment by rainliu** [comment]
Do you have code example? Peer connection should add track or transceiver before setRemoteDescription.

**Comment by tfoldi** [comment]
I have the same issue. I put together a client code where I can reproduce the issue, however, I do not access the server side.

the log and program are here:

https://gist.github.com/tfoldi/270ddfdf919bf035cd96652d4bb03622

**Comment by rainliu** [comment]
Just one unhandled RTCP doesn't mean an issue. Most likely remote accepted offer SDP, after sent back answer SDP, then immediately start to send RTCP packets before local receives answer SDP and setRemoteDescription.
```
webrtc/src/peer_connection/peer_connection_internal.rs:322 [WARN] 20:15:25.873716 - Incoming unhandled RTCP ssrc(305150496), on_track will not be fired

```

**Comment by tfoldi** [comment]
thank you for your quick answer, and sorry for hijacking the issue a bit. 

I understand that this alone might not be an issue, but in my case, the `peer_connection.on_track ` never fired at all. From the browser the same logic works well, I can get both the data channel and video (`recvonly`). From Rust, only the data channel was opened, and I received no video tracks. Maybe it's an issue with my code, I don't know.

**Comment by paultag** [comment]
Closing this issue; I never tracked it down to a specific acute cause; this is a mix of other (non-webrtc-rs) causes
