### ISSUE TITLE
Modify the webrtc RTCConfiguration and the get/setconfiguration for  fixing "whipinto and whepfrom iceserver" in our project

### ISSUE THREAD

**Issue by udrs** [webrtc-rs/webrtc#577]
we hope to modify this issue in our project(https://github.com/binbat/live777/issues/128), so we modified your "mod.rs" and "get/setconfiguration" function.
[ModifyRTCConfiguration.zip](https://github.com/user-attachments/files/15858131/ModifyRTCConfiguration.zip)

**Comment by udrs** [comment]
Thank you for you great job, look forward to your check and receive.

**Comment by rainliu** [comment]
thanks @udrs , the changes are merged as commit https://github.com/webrtc-rs/webrtc/commit/ae93e81a493c004b0270603d539ad9a40b7b3064
