### ISSUE TITLE
[TURN] disable "sfrlx" response for some TURN users

### ISSUE THREAD

**Issue by Ali-Mirghasemi** [webrtc-rs/webrtc#64]
hi 
is it possible to disable STUN response (sfrlx) for some users and force them to use relay?

**Comment by lolgesten** [comment]
@Ali-Mirghasemi maybe you can do this using the [`AgentConfig`](https://github.com/webrtc-rs/ice/blob/main/src/agent/agent_config.rs#L96-L97) of the ice agent?

In this array you can set the exact candidate types you allow.

**Comment by rainliu** [comment]
close this task as suggested above.
