### ISSUE TITLE
Upgrade to 0.12.0 broke TURN

### ISSUE THREAD

**Issue by ris-work** [webrtc-rs/webrtc#641]
Hey,
I just saw that an upgrade broke my turn setup. TURN no longer works after upgrading to 0.12.0. The TURN server is coturn. The coturn configuration is below.

```
bps-capacity=400000000
external-ip=103.97.203.7
fingerprint
listening-port=3478
lt-cred-mech
max-bps=1000000
max-port=65535
min-port=49152
realm=
relay-ip=103.97.203.7
syslog
tls-listening-port=5349
total-quota=0
user=user:password
```

When turn:[domain] and the credentials user:password is used, the login attempt does not even register with coturn and it fails ErrTurnCredentials. This happens regardless of whether `no-stun` or `fingerprint` is enabled or not, or a realm is set.

This has broken connectivity in two servers so far.

Thank you.

Regards,
Rishi

**Comment by ris-work** [comment]
Also, can confirm that the older builds work fine. Their logins register when run with `turnserver -v`.

**Comment by ris-work** [comment]
BTW additional details: none of the servers/clients have a public IP, so sometimes I _need_ TURN. They are all behind NAT. Sometimes STUN works, sometimes it doesn't, and it is expected. TURN is the only publicly available endpoint they can connect to.

**Comment by rainliu** [comment]
that's weird, TURN crate doesn't have actual code changes, only upgrades dependencies crates utils and stun.

 what's command for TURN client to connect to your coturn server?

**Comment by ris-work** [comment]
@rainliu: I am sorry, I fixed it. It was that multiple versions of the `turn` crate were present and the removal of CredentialType along with an older version being used with a newer `webrtc` crate caused this issue.

Thank you for the immediate response. Wish you success with this project!

Regards,
Rishikeshan S/L

**Comment by ris-work** [comment]
Pull request for removing leftover ErrTurnCredential: #644 
Thank you!
