### ISSUE TITLE
[ICE/STUN] replace crc32fast with crc

### ISSUE THREAD

**Issue by rainliu** [webrtc-rs/webrtc#67]
crc32fast should be replaced with crc crate, due to crc32fast issue found in sctp crate

**Comment by u-03c9** [comment]
Hi, can I try tackling this issue? also, is there a reason for using `crc` 1.8.1 instead of 2.0?

**Comment by rainliu** [comment]
sure. It is better to use the latest version of crc.

**Comment by rainliu** [comment]
@u-03c9 , I assign this task to you. You can also upgrade crc in sctp crate to the latest version.

**Comment by u-03c9** [comment]
I am a beginner. So, please let me know if the code needs any modifications.

**Comment by rainliu** [comment]
LGTM, accepted all PRs.

**Comment by rainliu** [comment]
Thank you for the fix
