### ISSUE TITLE
[STUN] Coturn server discards TURN packets when the FINGERPRINT attribute is present

### ISSUE THREAD

**Issue by Andrepuel** [webrtc-rs/webrtc#75]
I did a simple test with using turn crate where I communicated with a TURN server running Coturn software.

Most of the packets my turn client sent to the server were discarded. When I commented out the FINGERPRINT attribute on the source code, i.e. the STUN packets will not contain FINGERPRINT attribute anymore, then the issue is solved. I can do a full communication using the TURN server.

Right now, I still don't know why coturn did discard packets with the FINGERPRINT attribute. But removing this attribute fixes the problem.

**Comment by rainliu** [comment]
According to https://datatracker.ietf.org/doc/html/rfc8489#section-6.3, 
"If the FINGERPRINT extension is being used, the agent checks that the FINGERPRINT attribute is present and contains the correct value.  If any errors are detected, the message is silently discarded."

It may be due to CRC computing issue for FINGERPRINT? (https://datatracker.ietf.org/doc/html/rfc8489#section-14.7)

Does anyone want to investigate this issue?

**Comment by Andrepuel** [comment]
I've compared the fingerprint code with the one on https://github.com/jselbie/stunserver and found out that the CRC algorithm used there is different.

The following patch makes the problem go away:

    diff --git a/src/fingerprint.rs b/src/fingerprint.rs
    index 8b68166..5659512 100644
    --- a/src/fingerprint.rs
    +++ b/src/fingerprint.rs
    @@ -31,7 +31,8 @@ const FINGERPRINT_SIZE: usize = 4; // 32 bit
    // the 32-bit value 0x5354554e (the XOR helps in cases where an
    // application packet is also using CRC-32 in it).
    pub fn fingerprint_value(b: &[u8]) -> u32 {
    -    let checksum = Crc::<u32>::new(&CRC_32_ISCSI).checksum(b);
    +    let checksum = Crc::<u32>::new(&crc::CRC_32_ISO_HDLC).checksum(b);
    +    eprintln!("pre xor {:x}", checksum);
        checksum ^ FINGERPRINT_XOR_VALUE // XOR
    }
  
I will open a pull request fixing the unit tests and the code if you agree with this approach.

**Comment by rainliu** [comment]
stun/turn/ice crates are upgraded to v0.2.3
