### ISSUE TITLE
[TURN] Spams Channel-Bind requests every 5 minutes

### ISSUE THREAD

**Issue by Andrepuel** [webrtc-rs/webrtc#80]
Please observe the timestamp on the Channel-Bind requests.
![image](https://user-images.githubusercontent.com/1234937/129419400-cb30aa26-bc69-4554-8566-643cf5cd43fa.png)

These requests were done one after the other. No actual data was transferred while this "burst" was happening. Once all the channel-bind's were done.

I will investigate the source code, but I believe that while the channel-bind was still in progress, every data packet triggered a new channel bind request. I will add more information soon.

**Comment by Andrepuel** [comment]
By inspecting the code I think that the problem could be here:

https://sourcegraph.com/github.com/webrtc-rs/turn@1433931e813fa2d17a60c6a8b7a4e8f8f9683d14/-/blob/src/client/relay_conn.rs?L328

The state is set to Refresh within the `tokio::spawn`, depending on how long it takes for the tokio to actually start executing the future, we would have other calls to `send_to` being called and spawing the same future.

We could set the state before spawning the subtask, or we could check if the state is already Refresh when we set it within the subtask.

**Comment by rainliu** [comment]
Thanks for investigating this issue, could you submit a PR to fix this issue?

**Comment by Andrepuel** [comment]
Right away
