### ISSUE TITLE
[WebRTC] Need examples of Webrtc 

### ISSUE THREAD

**Issue by chet-hub** [webrtc-rs/webrtc#81]
Please add examples for this project

**Comment by rainliu** [comment]
Sure, but have to wait unit this crate hits v0.1.0

**Comment by rainliu** [comment]
@chet-hub , I have started adding examples of how to use webrtc-rs for both media and data channel APIs

Now, examples of data channels API are ready.

More examples of media API are on the way.

**Comment by rainliu** [comment]
all examples are added in https://github.com/webrtc-rs/webrtc/tree/master/examples
