### ISSUE TITLE
[DTLS] webrtc-rs <-> pion interop fail due to decrypt failed

### ISSUE THREAD

**Issue by rainliu** [webrtc-rs/webrtc#85]
Case 1: webrtc-rs as server,  Pion as client

git clone https://github.com/webrtc-rs/dtls
git clone https://github.com/pion/dtls

1. Run webrtc-rs's listen/selfsign:
    cargo run --example listen_selfsign
2.  Run pion's dial/selfsign:
    go run examples/dial/selfsign

listening 127.0.0.1:4444...
type 'exit' to shutdown gracefully
src/handshaker.rs:201 [TRACE] 21:23:27.753983 - [handshake:server] Flight 0: Preparing
src/handshaker.rs:201 [TRACE] 21:23:27.754107 - [handshake:server] Flight 0: Sending
src/handshaker.rs:201 [TRACE] 21:23:27.754200 - [handshake:server] Flight 0: Waiting
src/conn/mod.rs:996 [TRACE] 21:23:27.754338 - Recv [handshake:server] -> ClientHello (epoch: 0, seq: 0)
src/flight/flight0.rs:83 [DEBUG] 21:23:27.754508 - [handshake:server] use cipher suite: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
src/handshaker.rs:342 [TRACE] 21:23:27.754759 - [handshake:server] Flight 0 -> Flight 2
src/handshaker.rs:201 [TRACE] 21:23:27.754793 - [handshake:server] Flight 2: Preparing
src/handshaker.rs:201 [TRACE] 21:23:27.754818 - [handshake:server] Flight 2: Sending
src/conn/mod.rs:539 [TRACE] 21:23:27.754891 - Send [handshake:server] -> HelloVerifyRequest (epoch: 0, seq: 0)
src/handshaker.rs:201 [TRACE] 21:23:27.755027 - [handshake:server] Flight 2: Waiting
src/conn/mod.rs:996 [TRACE] 21:23:27.755298 - Recv [handshake:server] -> ClientHello (epoch: 0, seq: 1)
src/handshaker.rs:342 [TRACE] 21:23:27.755461 - [handshake:server] Flight 2 -> Flight 4
src/handshaker.rs:201 [TRACE] 21:23:27.755495 - [handshake:server] Flight 4: Preparing
src/handshaker.rs:201 [TRACE] 21:23:27.755698 - [handshake:server] Flight 4: Sending
src/conn/mod.rs:539 [TRACE] 21:23:27.755808 - Send [handshake:server] -> ServerHello (epoch: 0, seq: 1)
src/conn/mod.rs:539 [TRACE] 21:23:27.755883 - Send [handshake:server] -> TypeCertificate (epoch: 0, seq: 2)
src/conn/mod.rs:539 [TRACE] 21:23:27.755930 - Send [handshake:server] -> ServerKeyExchange (epoch: 0, seq: 3)
src/conn/mod.rs:539 [TRACE] 21:23:27.755970 - Send [handshake:server] -> ServerHelloDone (epoch: 0, seq: 4)
src/handshaker.rs:201 [TRACE] 21:23:27.756095 - [handshake:server] Flight 4: Waiting
src/conn/mod.rs:996 [TRACE] 21:23:27.756860 - Recv [handshake:server] -> ClientKeyExchange (epoch: 0, seq: 2)
src/conn/mod.rs:1075 [DEBUG] 21:23:27.756934 - server: CipherSuite not initialized, queuing packet
src/conn/mod.rs:912 [DEBUG] 21:23:27.756962 - server: received packet of next epoch, queuing packet
src/conn/mod.rs:1085 [TRACE] 21:23:27.758005 - server: <- ChangeCipherSpec (epoch: 1)
**_src/conn/mod.rs:969 [DEBUG] 21:23:27.758124 - server: decrypt failed: aead::Error with TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256_**

**Comment by rainliu** [comment]
Case 2:  webrtc-rs as client, Pion as server:

1. Run pion's listen/selfsign:
go run examples/listen/selfsign

2. Run webrtc-rs's dail/selfsign:
cargo run --example dail_selfsign


Listening
dtls TRACE: 21:29:40.868565 conn.go:268: Handshake begin...
dtls TRACE: 21:29:40.868684 handshaker.go:163: [handshake:server] Flight 0: Preparing
dtls TRACE: 21:29:40.868698 handshaker.go:163: [handshake:server] Flight 0: Sending
dtls TRACE: 21:29:40.868703 handshaker.go:163: [handshake:server] Flight 0: Waiting
dtls TRACE: 21:29:40.868761 handshaker.go:279: [handshake:server] Flight 0 -> Flight 2
dtls TRACE: 21:29:40.868782 handshaker.go:163: [handshake:server] Flight 2: Preparing
dtls TRACE: 21:29:40.868804 handshaker.go:163: [handshake:server] Flight 2: Sending
dtls TRACE: 21:29:40.868816 conn.go:444: [handshake:server] -> HelloVerifyRequest (epoch: 0, seq: 0)
dtls TRACE: 21:29:40.868891 handshaker.go:163: [handshake:server] Flight 2: Waiting
dtls TRACE: 21:29:40.870227 handshaker.go:279: [handshake:server] Flight 2 -> Flight 4
dtls TRACE: 21:29:40.870270 handshaker.go:163: [handshake:server] Flight 4: Preparing
dtls TRACE: 21:29:40.870473 handshaker.go:163: [handshake:server] Flight 4: Sending
dtls TRACE: 21:29:40.870488 conn.go:444: [handshake:server] -> ServerHello (epoch: 0, seq: 1)
dtls TRACE: 21:29:40.870506 conn.go:444: [handshake:server] -> TypeCertificate (epoch: 0, seq: 2)
dtls TRACE: 21:29:40.870523 conn.go:444: [handshake:server] -> ServerKeyExchange (epoch: 0, seq: 3)
dtls TRACE: 21:29:40.870531 conn.go:444: [handshake:server] -> ServerHelloDone (epoch: 0, seq: 4)
dtls TRACE: 21:29:40.870610 handshaker.go:163: [handshake:server] Flight 4: Waiting
dtls DEBUG: 21:29:40.879695 conn.go:793: CipherSuite not initialized, queuing packet
dtls DEBUG: 21:29:40.879720 conn.go:715: received packet of next epoch, queuing packet
dtls TRACE: 21:29:40.879915 conn.go:799: server: <- ChangeCipherSpec (epoch: 1)
dtls DEBUG: 21:29:40.879934 conn.go:748: server: decrypt failed: dtls temporary: failed to decrypt packet: cipher: message authentication failed

**Comment by rainliu** [comment]
Now GCM crypto suite works well, but CBC still fail due to another issue. Looks like fragment handling

**Comment by rainliu** [comment]
More debug info in CBC issue:

Here is Pion's CBC encrypt:

tls TRACE: 21:47:48.044541 conn.go:417: [handshake:client] -> Finished (epoch: 1, seq: 3)
dtls DEBUG: 21:47:48.044553 conn.go:547: [handshake:client] -> processHandshakePacket before len() 37, [22 254 253 0 1 0 0 0 0 0 0 0 24 20 0 0 12 0 3 0 0 0 0 0 12 61 238 20 207 92 160 201 65 129 182 245 106]
dtls DEBUG: 21:47:48.044573 conn.go:550: [handshake:client] -> processHandshakePacket after len() 77, [22 254 253 0 1 0 0 0 0 0 0 0 64 23 44 2 103 155 223 127 244 33 250 155 241 161 53 31 21 141 124 255 155 64 19 167 186 60 16 59 217 46 255 32 163 251 242 236 192 168 108 77 111 224 74 228 105 254 189 254 87 71 135 235 148 30 251 59 85 128 225 105 37 122 64 233 79]


But webrtc-rs's CBC decrypt:
src/conn/mod.rs:985 [DEBUG] 21:47:48.046913 - enqueue false: before decrypt, pkt.len() 77: [22, 254, 253, 0, 1, 0, 0, 0, 0, 0, 0, 0, 64, 23, 44, 2, 103, 155, 223, 127, 244, 33, 250, 155, 241, 161, 53, 31, 21, 141, 124, 255, 155, 64, 19, 167, 186, 60, 16, 59, 217, 46, 255, 32, 163, 251, 242, 236, 192, 168, 108, 77, 111, 224, 74, 228, 105, 254, 189, 254, 87, 71, 135, 235, 148, 30, 251, 59, 85, 128, 225, 105, 37, 122, 64, 233, 79]
src/conn/mod.rs:1006 [DEBUG] 21:47:48.047027 - enqueue false: after decrypt, pkt.len() 0, pkt.len() 74: [22, 254, 253, 0, 1, 0, 0, 0, 0, 0, 0, 0, 64, 251, 169, 163, 246, 183, 223, 111, 242, 42, 246, 183, 83, 253, 22, 193, 23, 20, 0, 0, 12, 0, 3, 0, 0, 0, 0, 0, 12, 61, 238, 20, 207, 92, 160, 201, 65, 129, 182, 245, 106, 200, 59, 2, 106, 142, 115, 13, 181, 130, 236, 26, 33, 106, 199, 111, 42, 192, 189, 91, 29, 3]

**Comment by Andrepuel** [comment]
https://github.com/Andrepuel/dtls/commit/f8c06ae3a5677b075f4cc56f1f00f28c4ce125c5

We are missing IV handling and HMAC handling on decrypt.

Besides that, Pion is not implementing PCKS7 as we are expecting on our side.
