### ISSUE TITLE
[WebRTC] fix play-from-disk example no sound issue in www, even audio track is sent to www

### ISSUE THREAD

**Issue by rainliu** [webrtc-rs/webrtc#96]

**Comment by englishm** [comment]
This appears to be a sync issue. The audio is present in the SDP (and this matches what pion offers as well):
```
...
m=audio 9 UDP/TLS/RTP/SAVPF 111 9 0 8
...
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
...
```

Audio data is definitely being sent as well. In some cases it's even possible to briefly hear some audio at the very beginning of playback.

Testing the same 5 second clip with both pion and webrtc-rs, the first difference I notice in webrtc-internals is that for the RTCInboundRTPAudioStream stats graph pion's shows some jitter whereas the webrtc-rs playback shows none at all.

**Comment by rainliu** [comment]
From chrome://webrtc-internals/,
pion's play-from-disk has non-zero audioOutputLevel output,

but webrtc-rs has always zero value audioOutputLevel.
