### ISSUE TITLE
[WebRTC] double check simulcast example and play-from-disk-renegotiation example

### ISSUE THREAD

**Issue by rainliu** [webrtc-rs/webrtc#97]
Pion's simulcast example can receives two streams with rid = "f" and "h"
~~and  play-from-disk-renegotiation example  has video grid when click add video multiple times.~~

**Comment by rainliu** [comment]
double check 
1). why simulcast example always receives one stream with rid="f" (full resolution)
2). why play-from-disk-renegotiation example can't add more grid

**Comment by cloudwebrtc** [comment]
> 2). why play-from-disk-renegotiation example can't add more grid

fixed by https://github.com/webrtc-rs/webrtc/pull/98.

**Comment by rainliu** [comment]
for 1). why simulcast example always receives one stream with rid="f" (full resolution)

according to chrome://webrtc-internals/,  webrtc-rs's bweforvideo
googAvailableReceiveBandwidth | 255280
googAvailableSendBandwidth | 300000

but pion has more than 1.5M bandwidth.

Most like due to RTCP feedback is not enabled in webrtc-rs, which cause BWE can't ramp up.

Will create another task to track RTCP feedback feature.








googActualEncBitrate | 75344
googAvailableReceiveBandwidth | 247541
googAvailableSendBandwidth | 300000
googBucketDelay | 0
googRetransmitBitrate | 0
googTargetEncBitrate | 300000
googTransmitBitrate

<br class="Apple-interchange-newline">

**Comment by cloudwebrtc** [comment]
> 1). why simulcast example always receives one stream with rid="f" (full resolution)

My guess is that on_track is not triggered, because I have the same problem when testing the `reflect` example. When I try to add audio/video and echo at the same time, I can only trigger the first track.

```
Press ctlr-c to stop
Peer Connection State has changed: connected
Track rid = f has started
enter track loop f
Sending pli for stream with rid: f, ssrc: 1697313055
Sending pli for stream with rid: f, ssrc: 1697313055
Sending pli for stream with rid: f, ssrc: 1697313055
Sending pli for stream with rid: f, ssrc: 1697313055
Sending pli for stream with rid: f, ssrc: 1697313055
Sending pli for stream with rid: f, ssrc: 1697313055
```

**Comment by cloudwebrtc** [comment]
When I wait for about 1 minute after connecting, h track will be triggered to display. Since then, there have been two tracks f|h.

**Comment by cloudwebrtc** [comment]
In the implementation of libwebrtc, when we setRemoteDescription, on_track will be triggered (before the ice connection), and then after receiving the data, `track.onunmuted` will be triggered, which means there is data coming.  the `on_track` of pion, webrtc-rs needs track will be triggered when data is received, 

So the problem is here, if we can’t receive the other party’s track, we can’t send FIR/PLI in the first time

**Comment by cloudwebrtc** [comment]
Anyway, I will find a way to figure out the problem.

**Comment by rainliu** [comment]
> > 1). why simulcast example always receives one stream with rid="f" (full resolution)
> 
> My guess is that on_track is not triggered, because I have the same problem when testing the `reflect` example. When I try to add audio/video and echo at the same time, I can only trigger the first track.
> 
> ```
> Press ctlr-c to stop
> Peer Connection State has changed: connected
> Track rid = f has started
> enter track loop f
> Sending pli for stream with rid: f, ssrc: 1697313055
> Sending pli for stream with rid: f, ssrc: 1697313055
> Sending pli for stream with rid: f, ssrc: 1697313055
> Sending pli for stream with rid: f, ssrc: 1697313055
> Sending pli for stream with rid: f, ssrc: 1697313055
> Sending pli for stream with rid: f, ssrc: 1697313055
> ```

with regard to "reflect" example with audio/video tracks issues, could you check my last commit# https://github.com/webrtc-rs/webrtc/commit/b5824ce5f92a365b7398ae029b20ce460d13ed47 ?

The issue of on_track() can't do long-loop job, we have to tokio::spawn a new task to handle the long-loop job.

**Comment by cloudwebrtc** [comment]
> with regard to "reflect" example with audio/video tracks issues, could you check my last commit# [b5824ce](https://github.com/webrtc-rs/webrtc/commit/b5824ce5f92a365b7398ae029b20ce460d13ed47) ? Whether it can fix your issues in your "reflect" example. The fix is similar to "save-to-disk" example.

cool, I will check

**Comment by cloudwebrtc** [comment]
@rainliu Hey, I added audio track support for `reflect` based on your submission, which works perfectly.
will create a PR later.

https://github.com/cloudwebrtc/webrtc-rs/commit/5cea06234167239b0ca60347043aae9caeb4f6e7

**Comment by rainliu** [comment]
> @rainliu Hey, I added audio track support for `reflect` based on your commit, which works perfectly.
> will create a PR later.
> 
> [cloudwebrtc@b0c0d19](https://github.com/cloudwebrtc/webrtc-rs/commit/b0c0d194974c6be3cd80f0c11c7f317c25268673)

cool!

let's close this task, and track simulcast issue in https://github.com/webrtc-rs/webrtc/issues/99
